### PR TITLE
Genshin Impact international release (3 ways)

### PR DESCRIPTION
**Pull request by cybik**
This would add Genshin Impact "Overseas" (Non-CN is considered "overseas" by Hoyoverse for obvious reasons) to the ULWGL database, under the ID "ulwgl-genshin", in three variants:

* Baseline
* Epic Game Store
* Google Play

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
the ulwgl id needs to be the exact same for all 3. they are sorted by store, not ulwgl id. ulwgl serves as basically just a unique id PER GAME. not per different distributions of the game.

**Comment by GloriousEggroll** [comment]
also -- the play store is for android, its not using wine and shouldnt be listed here.

**Comment by GloriousEggroll** [comment]
fwiw just make the  id ulwgl-genshin, it's easier to understand.

**Comment by cybik** [comment]
> the play store version is for android

Actually it's not. If someone browses to the Play Store with a Windows UserAgent, they can download a Google Play PC installer that installs the PC version and uses Google as the payment processor.

To wit: I set my Useragent to Windows 10 and browsed to [the Google Play page for Genshin](https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact), and they offer a Windows installer.
Screenshot_20240123_211758

This is the installer I used for my current Steam non-store entry for the game.

> fwiw just make the id ulwgl-genshin, it's easier to understand.

Done.

**Comment by GloriousEggroll** [comment]
> > the play store version is for android
> 
> Actually it's not. If someone browses to the Play Store's Genshin Impact entry using a Windows UserAgent, they can download a Google Play PC installer that installs the PC version and uses Google as the payment processor.
> 
> To wit: I set my Useragent to Windows 10 and browsed to [the game's Google Play page](https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact), and they offer a Windows installer. Screenshot_20240123_211758
> 
> This is the installer I used for my current Steam non-store entry for the game. (Pardon my ~fontainois~french)
> 
> > fwiw just make the id ulwgl-genshin, it's easier to understand.
> 
> Done.

neat, didnt know that, sorry i thought it was for the android version. regardles if its not a storefront thats built into another tool like heroic/lutris have such as gog, amazon, battlenet, ea, uplay and so on then it should use 'none' as the store because it uses the same fixes as the standalone.  fix that and everything else is good

**Comment by cybik** [comment]
The Play Store variant has no integration into Heroic or any other tool, as you say.

Edited.

**Pull request merged**
